project_name: ticker
before:
  hooks:
    - go mod download
builds:
  - id: build-upx
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    hooks:
      post:
        - upx "{{ .Path }}"
  - id: build
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
archives:
  - 
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    replacements:
      darwin: mac
snapshot:
  name_template: "{{ .Tag }}-next"
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
release:
  github:
      owner: achannarasappa
      name: ticker
brews:
  -
    name: ticker
    tap:
      owner: achannarasappa
      name: tap
    commit_author:
      name: achannarasappa
      email: git@ani.dev
    homepage: "https://github.com/achannarasappa/ticker"
    description: "Terminal stock ticker with live updates and position tracking"
    license: "GPLv3"
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
    - "achannarasappa/ticker:{{ .Tag }}"
    - "achannarasappa/ticker:v{{ .Major }}"
    - "achannarasappa/ticker:v{{ .Major }}.{{ .Minor }}"
    - "achannarasappa/ticker:latest"
snapcrafts:
  -
    id: ticker
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: mac
    publish: true
    summary: Terminal stock watcher and stock position tracker
    description: |
      Features:
      Live stock price quotes
      Track value of your stock positions
      Support for multiple cost basis lots
      Support for pre and post market price quotes

    grade: stable
    confinement: strict
    license: 	GPL-3.0-only
    apps:
      ticker:
        command: bin/ticker
        plugs:
          - network