# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - 
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    hooks:
      post:
        - upx "{{ .Path }}"
archives:
  - 
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: mac
      linux: linux
      amd64: 64-bit
      386: 32-bit
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  github:
      owner: achannarasappa
      name: ticker
  draft: true